### ISSUE TITLE
Input Combo Mappings

### ISSUE THREAD

**Issue by berksedatk** [isXander/Controlify#265] opened 2024-03-31 12:43 UTC
**Is your feature request related to a problem? Please describe.**
While playing on a server called Wynncraft (a MMOPRG server) we commonly use a mod called Wynntills that allows us to view the map, cast spells easily, track quests easily. There is already a mod called Controlify Wynn that adds compatability with the server, but while i was remapping keybinds to which i desire i realized a really important feature missing, combo mappings. 

**Describe the solution you'd like**
Being able to map 3 keys being pushed at the same time to trigger a command. To confirm the mapping is done you press the "GUI Abstract Action 1" key down. 

**Describe alternatives you've considered**
I believe there isn't a alternative for combo mappings.

**Additional context**
Not just for the server that im playing on but this would open so many posibilities for modded controller support. For examble Xaero's Minimap you can have LB + up to open your map, LB + down for quick waypoints. Or for Backpacks mod you could have RB + X to open your backpack, etc. Even for core Minecraft gameplay, you can have stuff like Open Advancements set to LT + down or Toggle Perspective RT + LT something like that if you are interested.

**Comment by isXander** [comment] 2024-04-10 21:14
Duplicate of #226

**Closed by isXander** 2024-04-10 21:14 UTC
Labels: enhancement
