### ISSUE TITLE
Spams dig button on Steam Deck [Bug]  

### ISSUE THREAD

**Issue by ColeTDeR** [isXander/Controlify#102] opened 2023-07-04 17:05 UTC
### Current Behaviour

When I use right trigger to try to dig a block, the button seems to be held in-game despite me not holding the button, as of I was constantly holding down right trigger.

### Expected Behaviour

When after releasing ZR I stop digging 

### Reproduction Steps

Use Controlify on Steam Deck

Set up controls as "Gamepad with Joystick Trackpad"

Use Controlify to calibrate joysticks

Create a world and try to start breaking a block

### Mod Version

1.3.1+1.20

### Controller

issues

### Bluetooth

- [ ] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment] 2023-07-04 20:34
Duplicate of #74

**Closed by isXander** 2023-07-04 20:34 UTC
Labels: bug
