### ISSUE TITLE
[Bug] Pressing B to exit out of GUI's drops item when drop item is paired to B

### ISSUE THREAD

**Issue by Jashi77** [isXander/Controlify#103] opened 2023-07-05 00:54 UTC
### Current Behaviour

Pressing B to exit out of a GUI which is the default keybind will also activate whatever other action is binded to B, like dropping an item, which I had it set to that since it's how the legacy console versions were mapped, and I'm a sucker for nostaglia.

### Expected Behaviour

I expected to be able to just leave inventory screens without hassle but it's really annoying dropping items I'm holding.

### Reproduction Steps

Map B to Drop Item (like legacy console)
Open Inventory
Close Inventory with item in hand

### Mod Version

1.3.1 1.20 and 1.4.0 1.20

### Controller

Xbox Series X Wired

### Bluetooth

- [ ] Yes

### Operating System

Windows

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment] 2023-07-08 09:51
Duplicate of #88

**Closed by isXander** 2023-07-08 09:51 UTC
Labels: bug
