### ISSUE TITLE
[Bug] Crash on Controller connecting

### ISSUE THREAD

**Issue by Yeetov** [isXander/Controlify#193] opened 2023-11-19 16:32 UTC
### Current Behaviour

When I go into settings in Controlify, my controller is not detected and when I connect it again, it crashes the game.
(I have Not Enough Crashes so it is fine)

### Expected Behaviour

Open up the controller configuration or something once the controller is connected.

### Screenshots

![Not Enough Crashes Screen](https://github.com/isXander/Controlify/assets/69159547/4a05846e-857f-452d-b44b-feb162b1baeb)

### Reproduction Steps

1. Launch Minecraft
2. Open Mod menu
3. Click on Controlify settings button
4. Unplug the controller because it says (No controllers connected)
5. Replug the controller into computer
6. Crash

### Logs

```shell
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-11-19 16:14:46
Description: Creating controller #0

java.lang.IllegalArgumentException: Joystick 0 is not a gamepad!
	at dev.isxander.controlify.controller.gamepad.GamepadController.<init>(GamepadController.java:35)
	at dev.isxander.controlify.controllermanager.AbstractControllerManager.createOrGet(AbstractControllerManager.java:57)
	at dev.isxander.controlify.controllermanager.SDLControllerManager.tick(SDLControllerManager.java:60)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:423)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$bnj000$fabric-lifecycle-events-v1$onStartTick(class_310.java:13101)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.isxander.controlify.controller.gamepad.GamepadController.<init>(GamepadController.java:35)
	at dev.isxander.controlify.controllermanager.AbstractControllerManager.createOrGet(AbstractControllerManager.java:57)
	at dev.isxander.controlify.controllermanager.SDLControllerManager.tick(SDLControllerManager.java:60)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:423)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$bnj000$fabric-lifecycle-events-v1$onStartTick(class_310.java:13101)

-- Controller Info --
Details:
	Joystick ID: 0
	Controller identification: ControllerType[friendlyName=Unknown, mappingId=unknown, themeId=unknown, forceJoystick=false, dontLoad=false]
	HID path: 00680103-0000-0188-0000-0e6f33f80003
	HID service status: Enabled
	GLFW name: PDP Afterglow Deluxe+ Audio Wired Controller
Stacktrace:
	at dev.isxander.controlify.controllermanager.AbstractControllerManager.createOrGet(AbstractControllerManager.java:57)
	at dev.isxander.controlify.controllermanager.SDLControllerManager.tick(SDLControllerManager.java:60)
	at dev.isxander.controlify.Controlify.tick(Controlify.java:423)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$bnj000$fabric-lifecycle-events-v1$onStartTick(class_310.java:13101)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/FreshAnimations_v1.8.1.zip, file/wither totem.zip, presencefootsteps:default_sound_pack, minecraft:supporteatinganimation
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2488)
	at net.minecraft.class_310.method_1514(class_310.java:875)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1388612496 bytes (1324 MiB) / 1933574144 bytes (1844 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Virtual memory max (MB): 18078.21
	Virtual memory used (MB): 12468.60
	Swap memory total (MB): 10008.23
	Swap memory used (MB): 1384.06
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20.2
		architectury: Architectury 10.0.14
		armorful: Armorful 2.0.3+1.20.2
			static-content: Static Content 1.1.0-1.18.2
				staticdata-fabric: Static Data 1.2.0
		auudio: Auudio 1.0.3
		bedrockify: BedrockIfy 1.9.1+mc1.20.2
			panorama_screens: Panorama Screens 1.0+fabric+mc1.20.2
		better_end_sky: Better End Sky 0.2.1+1.20
		better_totem_of_undying: Better Totem of Undying [FABRIC] 1.1.1
			cardinal-components-base: Cardinal Components API (base) 5.3.0
			cardinal-components-entity: Cardinal Components API (entities) 5.3.0
		bettermounthud: Better Mount HUD 1.2.2
		betterstats: Better Statistics Screen 3.5.1+fabric-1.20.2
			tcdcommons: TCD Commons API 3.5+fabric-1.20.2
		betterthirdperson: Better Third Person 1.9.0
		blur: Blur (Fabric) 3.1.1
			midnightlib: MidnightLib 1.5.0
			satin: Satin 1.14.0
		boathud: BoatHud 1.1.5
		capes: Capes 1.5.3+1.20.2
		chat_heads: Chat Heads 0.10.25
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0
		cloth-config: Cloth Config v12 12.0.111
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.7
		controlify: Controlify 1.7.0+1.20.2
			dev_isxander_libsdl4j: libsdl4j 2.28.2-11
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_quilt-json5: quilt-json5 1.0.3
		craftify: Craftify 1.12.0
			elementa: Elementa 590
			universalcraft: UniversalCraft 316
			vigilance: Vigilance 284
		debugify: Debugify 1.20.2+1.0
		do_a_barrel_roll: Do a Barrel Roll 3.3.7+1.20.2
			cicada: CICADA 0.5.0+1.20.2-plus
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.1
		draggable_lists: Draggable Lists 1.0.2
		dynamiclights: Dynamic Lights 1.7+mod
		eatinganimationid: Eating Animation 1.20+1.9.5-CMDfix
		enhancedgroups: Simple Voice Chat Enhanced Groups 1.20.2-1.4.0
		entity_model_features: Entity Model Features 1.1.0
		entity_texture_features: Entity Texture Features 4.6.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		fabric-api: Fabric API 0.90.7+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.75+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.5+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.11+bff13c85a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.8+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.6+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.10+e3d2bf3fa0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.41+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.10+bb1ee60ea0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabric-language-kotlin: Fabric Language Kotlin 1.10.14+kotlin.1.9.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.1
		fabricloader: Fabric Loader 0.14.24
		fallingtree: FallingTree 5.0.3
		fancymenu: FancyMenu 2.14.10
		fixbookgui: Fix Book Gui Mod 1.5
		flash: Flash 2.0.0
			com_github_krlite_equator-v2_animation: Animation 2.6.0-mc1.20
			com_github_krlite_equator-v2_visual: Visual 2.6.0-mc1.20
		flow: Flow 1.2.1+1.20.2
		fmextension_audio: FancyMenu Audio Extension 1.1.2
		fog-looks-good-now: FogLooksGoodNow 1.3.2+1.20.2
			owo: oωo 0.11.3+1.20.2
		java: Java HotSpot(TM) 64-Bit Server VM 17
		konkrete: Konkrete 1.7.0
		leahs-immersive-thunder: Immersive Thunder 1.20.2+1.2.2
		make_bubbles_pop: Make Bubbles Pop Mod 0.2.0-fabric
		mcemote: Minecraft Emote 1.1.0
			com_github_vinrobot_webpdecoderjn_lib: lib 1.3
		minecraft: Minecraft 1.20.2
		modmenu: Mod Menu 8.0.0
		mru: Mineblock's Repeated Utilities 0.4.0+1.20.2
		netherportalspread: Nether Portal Spread 7.6
		notenoughanimations: NotEnoughAnimations 1.6.4
		notenoughcrashes: Not Enough Crashes 4.4.6+1.20.2
		oldmclogo: Old MC Logo 1.1.1
		pickupnotifications: Pickup Notifications 1.6.0
		presencefootsteps: Presence Footsteps 1.10.0
			kirin: Kirin UI 1.16.0+1.20.2
		realisticbees: Realistic Bees 3.6
		servercountryflags: Server Country Flags 1.9.0
		skinlayers: 3d Skin Layers 1.5.6-mc1.20.2
		smoothscrollingrefurbished: Smooth Scrolling Refurbished 1.1.1
		smoothswapping: Smooth Swapping 0.9.3.1
		snowundertrees: Snow Under Trees 2.0.0+1.20.2
		sodium: Sodium 0.5.3
		sprint-by-default: Sprint By Default 1.0.3
		spyglass_astronomy: Spyglass Astronomy 1.0.8-mc1.20.2
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.15
		telepistons: Telepistons 1.1.3
		visuality: Visuality 0.7.1+1.20
		voicechat: Simple Voice Chat 1.20.2-2.4.28
		wakes: Wakes 0.2.0
			blue_endless_jankson: jankson 1.2.2
		water_vision: Water Vision 1.0.0
		waveycapes: WaveyCapes 1.3.2
		woof: Woof 4.0.2+1.20.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.0-beta.1+1.20.2
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.12.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	JVM uptime in seconds: 235.068
	Launched Version: 1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Intel(R) UHD Graphics 630 GL version 3.2.0 - Build 26.20.100.7262, Intel
	Window size: 1280x697
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/FreshAnimations_v1.8.1.zip (incompatible), file/wither totem.zip, presencefootsteps:default_sound_pack, minecraft:supporteatinganimation (incompatible)
	Current Language: en_gb
	Locale: en_GB
	CPU: 6x Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Controlify (controlify), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1)
```

### Mod Version

v1.7.0+1.20.2 (Not beta)

### Controller

Afterglow Deluxe+ Audio Wired Controller (For Nintendo Switch)

### Bluetooth

- [ ] Yes

### Operating System

Windows

### Additional Information

The first time I had controlify, I clicked the download button that downloads the other libraries.
Minecraft was launched from PrismMC

### Just to make sure...

- [ ] Yes
- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment] 2023-11-26 00:10
Duplicate of #188

**Closed by isXander** 2023-11-26 00:10 UTC
Labels: bug
